- hosts: localhost
  gather_facts: False
  tasks:

  - name: Create plexguide network
    docker_network:
      name: plexguide

###--- Home Assistant Setup ---###
  - name: Setup Home Assistant
    docker_container:
      name: hass
      image: homeassistant/home-assistant
      pull: yes
      volumes:
        - /opt/appdata/hass/config:/config
        - /etc/localtime:/etc/localtime:ro
      restart_policy: always
      state: started
      env:
        PUID: "1000"
        GUID: "1000"
      labels:
        traefik.enable: "true"
        # traefik.frontend.redirect.entryPoint: "https"
        traefik.frontend.rule: "Host:home.wooster.xyz"
        traefik.port: "8123"
        traefik.docker.network: "plexguide"
      ports:
        - 8123:8123
      networks:
        - name: plexguide
          aliases:
            - hass

###--- MariaDb Setup ---###
#  - name: Setup MariaDb for Home Assistant
#    docker_container:
#      name: mariadb_hass
#      image: mariadb
#      volumes:
#        - mariadb:/var/lib/mysql
#        - /etc/localtime:/etc/localtime:ro
#      restart_policy: always
#      environment:
#        MYSQL_ROOT_PASSWORD: "woosterexposed"
#        MYSQL_DATABASE: "homeassistant"
#        MYSQL_USER: "hassdb"
#        MYSQL_USER: "woosterexposed"
#      networks:
#        - name: plexguide
#          aliases:
#            - mariadb_hass
#      state: started

##--- mosquitto Setup ---###
  - name: Setup mosquitto
    docker_container:
      name: mosquitto
      image: eclipse-mosquitto
      volumes:
        - /opt/appdata/mosquitto/config:/mosquitto/config
        - /opt/appdata/mosquitto/data:/mosquitto/data
        - /opt/appdata/mosquitto/log:/mosquitto/log
        # - mosquitto_config:/mosquitto/config
        # - mosquitto_data:/mosquitto/data
        # - mosquitto_log:/mosquitto/log
        # - /opt/appdata/mosquitto/mosquitto.conf:/mosquitto/mosquitto.conf
      restart_policy: always
      env:
        PUID: "1000"
        GUID: "1000"
#      labels:
#        traefik.enable: "true"
#        traefik.frontend.redirect.entryPoint: "https"
#        traefik.frontend.rule: "Host:mqtt.wooster.xyz"
#        traefik.port: "1883"
      ports:
        - 1883:1883
#        - 9001:9001
      networks:
        - name: plexguide
          aliases:
            - mosquitto
      state: started

###--- TasmoAdmin Setup ---###
 # tasmoadmin:
 #   container_name: tasmoadmin
 #   image: raymondmm/tasmoadmin
 #   volumes:
 #     - tasmoconfig:/data
 #   environment:
 #     - PUID=1000
 #     - GUID=1000
 #   labels:
 #     traefik.enable: "true"
 #     traefik.frontend.redirect.entryPoint: "https"
 #     traefik.frontend.rule: "Host:tasmoadmin.wooster.xyz"
 #     traefik.port: "80"
 #     traefik.docker.network: "plexguide"
 #   networks:
 #     - homeassistant
 #     - plexguide

#volumes:
#  nodereddata:
#  noderedmodules:
#  mariadb:
#  mosquitto_config:
#  mosquitto_data:
#  mosquitto_log:
#  tasmoconfig:

#networks:
#  homeassistant:
#    driver: bridge
#  plexguide:
#    external:
#      name: plexguide
          
###--- Node-red Setup ---###
#  nodered:
#    build: ./image
#    container_name: nodered
#    image: node-red-docker:v8
#    volumes:
#      - nodereddata:/data
#      - noderedmodules:/node_app/node_modules
#      - /etc/localtime:/etc/localtime:ro
#    restart: always
#    environment:
#      - PUID=1000
#      - GUID=1000
#    labels:
#      traefik.enable: "true"
#      traefik.frontend.redirect.entryPoint: "https"
#      traefik.frontend.rule: "Host:nodered.wooster.xyz"
#      traefik.port: "1880"
#      traefik.docker.network: "plexguide"
#    ports:
#      - 1880:1880
#    networks:
#      - homeassistant
#      - plexguide
