FROM nodered/node-red-docker:v8
RUN npm install https://github.com/zachowj/node-red-contrib-home-assistant-websocket \
    node-red-contrib-sunpos \
    node-red-contrib-light-scheduler \
    https://github.com/hardillb/node-red-node-geofence \
    https://github.com/hjespers/node-red-contrib-nest
